name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Scan, Push & Deploy
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ashup1997/flask-devops-app
      IMAGE_TAG: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG ./app

      - name: Trivy scan
        uses: aquasecurity/trivy-action@v0.11.2
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Push to DockerHub
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Deploy to EKS using Helm
        run: |
          helm upgrade --install myapp ./helm/myapp --namespace dev --create-namespace

